language: python
python:
- 3.5
script:
- echo building...
deploy:
  provider: pypi
  user: andykuszyk
  on:
    tags: true
    all_branches: true
  password:
    secure: luDDE8FIMcjwoUcO4UGtXNk2Z1MftgJ++v6JEIHJyQjOrv02N6MjVnBQUtkdvGIog60TSaloERXWedPn3WJAzq72To9xOx/r6MTPb1++UrSHpFMS+eoj7SvBQ6MDp/BSIfpeT9hRkBB0XqP81SBqTt/jG1QpVAetEs7OkAVP3SAyTxjVMPrphHbJNllwitSppMkLIx96DohyyZAoXE/ObUSeHT5bQUg+FeArM4SL98tAcAlbDfWQIk03Bv6UpVXWSreFJGDE7ISla1SE/k/tXi0XbXNjXY1+Qi8YeYOsBHJY//f8p14a6X/5oZaKA+BQ7mirBNKlwcVav4ucVg6mIDZ1wDYZ01dXHu5x3+N/bsFiHh7J90IvejWUJU+jAdAqh8duAQg1fJp331Yt1l/VTcmMvzdzcx0ean9iaZXX016uzW1QE51thQ7brawTKhSuA5rrpucRAsiegZ08GQAK/6gxqvyX+6hUYkf6kxTwMnK0PU5s11my8shY+LFheA0TB/qIM5ihaomeOMmLcP81goF+Z6n4++ujJFgiE5PTMEuVck26HdA//1K8JakFat3f4ua+fUg2zDda9JOwJGS5CRT7Ojj4WC9/yPfpOy2HkvGngtqgCOxnsXQ/tn51y75He5u25WQeW7j8aA0GNu4h9hG2kohG2SitsbRyoZfaFtQ=
